// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2OrAeqLx5shjjWY-Qa-HnpqeAc21VF1Q',
    appId: '1:493014158201:web:3e7596724e3b50b0517da8',
    messagingSenderId: '493014158201',
    projectId: 'vouch-tour-mobile-swd',
    authDomain: 'vouch-tour-mobile-swd.firebaseapp.com',
    databaseURL: 'https://vouch-tour-mobile-swd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vouch-tour-mobile-swd.appspot.com',
    measurementId: 'G-B0XKNQ8Y9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6mwAEq6_IL50oQAv7EZ7rN_12XoyZXoY',
    appId: '1:493014158201:android:9197a2c32598e31b517da8',
    messagingSenderId: '493014158201',
    projectId: 'vouch-tour-mobile-swd',
    databaseURL: 'https://vouch-tour-mobile-swd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vouch-tour-mobile-swd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn2eLkwbNwYzND6xL5b_-xHrcdh2_mx8Y',
    appId: '1:493014158201:ios:f9f1c33b24ef7895517da8',
    messagingSenderId: '493014158201',
    projectId: 'vouch-tour-mobile-swd',
    databaseURL: 'https://vouch-tour-mobile-swd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vouch-tour-mobile-swd.appspot.com',
    androidClientId: '493014158201-gs38cd35a7rds7bet4lu70jbnv9jl0ln.apps.googleusercontent.com',
    iosClientId: '493014158201-ung7g4bu0n0fattfuo26af7lkm5097l9.apps.googleusercontent.com',
    iosBundleId: 'com.groupswd.vouchTourMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn2eLkwbNwYzND6xL5b_-xHrcdh2_mx8Y',
    appId: '1:493014158201:ios:ca715a75be04a3e8517da8',
    messagingSenderId: '493014158201',
    projectId: 'vouch-tour-mobile-swd',
    databaseURL: 'https://vouch-tour-mobile-swd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vouch-tour-mobile-swd.appspot.com',
    androidClientId: '493014158201-gs38cd35a7rds7bet4lu70jbnv9jl0ln.apps.googleusercontent.com',
    iosClientId: '493014158201-n98jrqdliulodvi83kje662rdhnapa7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.vouchTourMobile',
  );
}
